"""create adventures and photos

Revision ID: 6ac062e3e15f
Revises: 6e586c150235
Create Date: 2026-07-15 11:33:57.884224

"""
from os import name
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac062e3e15f'
down_revision: Union[str, Sequence[str], None] = '6e586c150235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.Enum('hiking', 'sports', 'travel', 'food', 'outdoors', name='adventure_category'), nullable=False),
    sa.Column('status', sa.Enum('completed', 'wishlist', name='adventure_status'), server_default='completed', nullable=False),
    sa.Column('adventure_date', sa.Date(), nullable=False),
    sa.Column('location_name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)', name='ck_adventures_coordinates_pair'),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_adventures_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_adventures_longitude_range'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_adventures_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adventures_user_category', 'adventures', ['user_id', 'category'], unique=False)
    op.create_index('ix_adventures_user_date', 'adventures', ['user_id', 'adventure_date'], unique=False)
    op.create_index(op.f('ix_adventures_user_id'), 'adventures', ['user_id'], unique=False)
    op.create_table('adventure_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adventure_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0 AND position <= 4', name='ck_adventure_photos_position_range'),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adventure_id', 'position', name='uq_adventure_photos_adventure_position')
    )
    op.create_index('ix_adventure_photos_adventure_id', 'adventure_photos', ['adventure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adventure_photos_adventure_id', table_name='adventure_photos')
    op.drop_table('adventure_photos')
    op.drop_index(op.f('ix_adventures_user_id'), table_name='adventures')
    op.drop_index('ix_adventures_user_date', table_name='adventures')
    op.drop_index('ix_adventures_user_category', table_name='adventures')
    op.drop_table('adventures')

    sa.Enum(name="adventure_status").drop(op.get_bind(), checkfirst=True)

    sa.Enum(name="adventure_category").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
