"""add photo public ids

Revision ID: 9112ab3e6374
Revises: 6ac062e3e15f
Create Date: 2026-07-17 12:09:34.788595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9112ab3e6374'
down_revision: Union[str, Sequence[str], None] = '6ac062e3e15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure_photos', sa.Column('public_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint("uq_adventure_photos_public_id", 'adventure_photos', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_adventure_photos_public_id", 'adventure_photos', type_='unique')
    op.drop_column('adventure_photos', 'public_id')
    # ### end Alembic commands ###
