"""add adventure collections

Revision ID: b4a5870913c1
Revises: 9112ab3e6374
Create Date: 2026-07-20 11:58:04.461924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a5870913c1'
down_revision: Union[str, Sequence[str], None] = '9112ab3e6374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=40), server_default='map-outline', nullable=False),
    sa.Column('target_count', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_count >= 1 AND target_count <= 100', name='ck_collections_target_count_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='uq_collections_user_title')
    )
    op.create_index('ix_collections_user_created', 'collections', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('collection_adventures',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('adventure_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'adventure_id')
    )
    op.create_index('ix_collection_adventures_adventure_id', 'collection_adventures', ['adventure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collection_adventures_adventure_id', table_name='collection_adventures')
    op.drop_table('collection_adventures')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index('ix_collections_user_created', table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
